### ISSUE TITLE
Missing document

### ISSUE THREAD

**Issue by ssured** [nolanlawson/fruitdown#10]
This is the follow-up from https://github.com/pouchdb/pouchdb/pull/5064. Presumably the error happened in this leveldown driver, that's why it is reposted here.

The error happened on Mac Safari 9 (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9`) and was reported using Rollbar remote debugging. Sadly there is only limited information, the bug points to https://github.com/pouchdb/pouchdb/blob/fd880917cfdbdaf7fac60b7f36af00aa5dac4299/src/adapters/leveldb/index.js#L1128 stating `TypeError: undefined is not an object (evaluating 'metadata.id')`.

I'll keep an eye on this error happening again, until now I only had 1 occurrence. I was surprised it happened, maybe this information is too limited to figure out what happened, feel free to close then I'll reopen when more occurrences happen.

Thanks for making all the awesome open source software! I try to give back a little this way, even though I have a feeling it is lacking information. Cheers

**Comment by nolanlawson** [comment]
Thanks for reporting. I will try to get to this when I get a chance. It would be nice to have a reproducible test case (e.g. a Hello World app).
