### ISSUE TITLE
Can't find variable: fieldset

### ISSUE THREAD

**Issue by dsmeltz** [nolanlawson/fruitdown#4]
Not sure if this is really a FruitDOWN issue or a pouchdb issue using fruitdown, but I'll start here.

When attempting to use the FruitDOWN adapter I'm receiving the following error:

**ReferenceError: Can't find variable: fieldset**

Here's how I'm using the adapter:

new PouchDB(config.local, {size: 50, adapter: 'fruitdown'});

I'm trying to get PouchDB to work again in the latest Chrome (48) for iOS (9.2.1)

If you need anymore information, I'll try to dig up what I can.

Thanks,
Dan

**Comment by nolanlawson** [comment]
Can you provide a full stacktrace? My hunch is that it's not a FruitDOWN issue, since the variable `fieldset` isn't anywhere in the codebase.

**Comment by dsmeltz** [comment]
I think we'll have to wait for a new rev of Chrome for iOS.
We don't have any fieldset tags in our markup, but we still receive the following error.

[Chromium Error](https://code.google.com/p/chromium/issues/detail?id=570095)

I would say close this issue as a non-issue for fruitdown.

**Comment by nolanlawson** [comment]
OK, thanks!
